# Site settings
title: JKAN
description: A lightweight, backend-free open data portal, powered by Jekyll
baseurl: ""
demo_url: https://demo.jkan.io
repo_url: https://github.com/timwis/jkan

# Build settings
markdown: kramdown

collections:
  - features
  - implementations
  - installation

sass:
    sass_dir: _sass
